version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8082:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: 'spinpick-directus-key'
      SECRET: 'spinpick-directus-secret'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'spinpick123'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'http://localhost:5173'
      PUBLIC_URL: 'http://localhost:8082'